config/routes.rb
Project2::Application.routes.draw do

  devise_for :user, controllers: {omniauth_callbacks: "omniauth_callbacks", registrations: "registrations" }

  devise_scope :user do
    get '/login', to: 'devise/sessions#new'
  end

  resources :users, except: [:new, :create, :update, :edit] do
    resources :albums do
      resources :photos do
        member do
          post '/comment', action: 'create', controller: 'comments'
          post :like_wall
          post :unlike_wall
          post :like
          post :unlike
          get :download
        end
      end
    end
  end

  resources :comments
  resources :pages
  resources :local_photos, only: :show

  get '/photo_wall', to: 'photos#photo_wall', as: :photo_wall
  get '/my_profile', to: 'users#my_profile', as: :my_profile
  match 'search', to: 'search#index', via: [:get, :post], as: :search

  resources :albums do
    get 'page/:page', action: :index, on: :collection
  end

 get '/about', to: 'users#about', as: :about
 get '/thanks_for_registering', to: 'users#thanks_for_registering', as: :thanks_for_registering


  root to: 'photos#photo_wall'

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  attr_accessible :content, :user_id, :photo_id

  validates :content, presence: true, length:{maximum:500}

  belongs_to :user
  belongs_to :photo

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 load_and_authorize_resource
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])

  end

  # POST /comments
  # POST /comments.json
  def create
    params[:comment][:photo_id] = params[:id]
    params[:comment][:user_id] = current_user.id
    @comment = Comment.new(params[:comment])
    @photo = Photo.find(params[:id].to_i)

    respond_to do |format|
      if @comment.save
        CommentMailer.comment_notification(@photo, @comment, @comment.user).deliver
        photo_path = user_album_photo_path(@comment.photo.album.user.id, @comment.photo.album.id, @comment.photo.id)
        format.html { redirect_to photo_path, notice: 'Comment successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    photo = @comment.photo
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to user_album_photo_path(photo.album.user, photo.album, photo) }
      format.json { head :no_content }
    end
  end
end

app/views/comments/_form.html.erb
<%= form_for(@comment, url: comment_user_album_photo_path) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content, 'Leave a Comment:' %><br />
    <%= f.text_area :content, :autofocus => true, size: '100x3' %>
  </div>

  <div>
    <%= f.submit 'Submit', class: "btn btn-success btn-mini" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<div class="span8">
  <h1 class="inner_shadow">Editing comment</h1>

  <%= render 'form' %>
</div>

app/views/comments/index.html.erb
<div class="span8">
  <h1 class="inner_shadow">Listing comments</h1>

  <table class="table">
    <tr>
      <th>Content</th>
      <th>User</th>
      <th>Album</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

  <% @comments.each do |comment| %>
    <tr>
      <td><%= comment.content %></td>
      <td><%= comment.user %></td>
      <td><%= comment.album %></td>
      <td><%= link_to 'View', comment, class:"btn btn-info btn-mini" %></td>
      <td><%= link_to 'Edit', edit_comment_path(comment), class:"btn btn-warning btn-mini" %></td>
      <td><%= link_to 'Destroy', comment, class:"btn btn-danger btn-mini", method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </table>

  <br />
  <div class="links">
    <%= link_to 'New Comment', new_comment_path, class:"btn btn-success btn-large" %>
  </div>
</div>

app/views/comments/new.html.erb
<div class="span8">
  <h1 class="inner_shadow">New Comment</h1>

  <%= render 'form' %>
</div>

app/views/comments/show.html.erb
<div class="span8">
  <p id="notice"><%= notice %></p>

  <p>
    <b>Content:</b>
    <%= @comment.content %>
  </p>

  <p>
    <b>User:</b>
    <%= @comment.user %>
  </p>

  <p>
    <b>Album:</b>
    <%= @comment.album %>
  </p>

  <div class="links">
   <% if can? :edit, @comment %>
      <%= link_to 'Edit', edit_comment_path(@comment), class:"btn btn-warning btn-mini" %>
      <%= link_to 'Delete', destroy_comment_path(@comment), class:"btn btn-warning btn-mini" %>
    <% end %>
    <%= link_to 'Back', comments_path, class:"btn btn-inverse btn-mini" %>
  </div>
</div>