config/routes.rb
Project2::Application.routes.draw do

  devise_for :user, controllers: {omniauth_callbacks: "omniauth_callbacks", registrations: "registrations" }

  devise_scope :user do
    get '/login', to: 'devise/sessions#new'
  end

  resources :users, except: [:new, :create, :update, :edit] do
    resources :albums do
      resources :photos do
        member do
          post '/comment', action: 'create', controller: 'comments'
          post :like_wall
          post :unlike_wall
          post :like
          post :unlike
          get :download
        end
      end
    end
  end

  resources :comments
  resources :pages
  resources :local_photos, only: :show

  get '/photo_wall', to: 'photos#photo_wall', as: :photo_wall
  get '/my_profile', to: 'users#my_profile', as: :my_profile
  match 'search', to: 'search#index', via: [:get, :post], as: :search

  resources :albums do
    get 'page/:page', action: :index, on: :collection
  end

 get '/about', to: 'users#about', as: :about
 get '/thanks_for_registering', to: 'users#thanks_for_registering', as: :thanks_for_registering


  root to: 'photos#photo_wall'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  before_validation :downcase_username
  before_validation :set_default_role

  devise :database_authenticatable, :registerable, :omniauthable, :recoverable, :rememberable, :trackable, :validatable, :confirmable, omniauth_providers: [:google_oauth2]

  acts_as_voter

	attr_accessible :avatar, :biography, :email, :first_name, :last_name, :location, :role, :username, :password,:password_confirmation, :provider, :uid, :remember_me

	mount_uploader :avatar, AvatarUploader

	validates :first_name, presence: true, length:{minimum:2}
	validates :last_name, presence: true, length:{minimum:2}
	validates :username, presence: true, uniqueness: true, length:{maximum:15}
	# validates :email, presence: true, uniqueness: true => on: :create
	validates :biography, length: {maximum: 250,
		too_long: "%{count} characters is the maximum allowed." }

      validate :avatar_size_validation


	has_many :comments
	has_many :albums, dependent: :destroy
	has_many :photos, through: :albums, dependent: :destroy

	accepts_nested_attributes_for :albums

  def self.find_for_authentication(conditions)
    conditions[:username].downcase!
    super(conditions)
  end

	def role?(role)
		self.role == role
	end

  private
  def downcase_username
    self.username.downcase! if self.username
  end

  private
  def set_default_role
    self.role ||= 'registered'
  end


  private
  def avatar_size_validation
    errors[:avatar] << "should be less than 1MB" if avatar.size > (1.2).megabyte
  end

  def self.from_omniauth(auth)
    if user = User.find_by_email(auth.info.email)
      user.provider = auth.provider
      user.uid = auth.uid
      user
    else
      where(auth.slice(:provider, :uid)).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.first_name = auth.info.first_name
        user.last_name = auth.info.last_name
        user.username = auth.info.email
      end
    end
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_filter: authenticate_user
  load_and_authorize_resource
  before_filter :authenticate_user!, except: [:about, :thanks_for_registering]

  def about
    @admins = []
    @users = User.all
    @users.each do |user|
      if user.role == "admin"
        @admins << user
      end
    end
  end

 # GET /users
  # GET /users.json
  def index
    @users = User.order(:last_name).page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  def my_profile
    @user = current_user
    render :show
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>

    </div>
  <% end %>
  <div class="links">
    <%= link_to 'View', @user, class:"btn btn-info btn-mini" %>
    <%= link_to 'Back to Users', users_path, class:"btn btn-inverse btn-mini" %>
  </div>
  <br>
  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %><br />
  </div>
  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %><br />
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email, :autofocus => true %><br />
  </div>
  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %><br />
  </div>
  <div class="field">
    <%= f.file_field :avatar, :onchange =>"validateFiles(this);", :data => { :max_file_size => 1.megabyte }%>
     <%= f.label :avatar %><br/>
  </div>
  <div class="field">
    <%= f.label :biography %>
    <%= f.text_area :biography %><br />
  </div>
  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %><br />
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %><br />
  </div>
  <div class="field"> <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %><br />
  </div>
  <div class="links">
    <%= f.submit 'Submit', class: "btn btn-success btn-mini"  %>
    <%= link_to 'View', @user, class:"btn btn-info btn-mini" %>
    <%= link_to 'Back to Users', users_path, class:"btn btn-inverse btn-mini" %>
  </div>
<% end %>

app/views/users/about.html.erb
<div class="span12">

<%= content_for :page_title, 'About Us - Custom page title' %>
  <div class="row">
    <div id="team_info">
      <h1 class="inner_shadow">About 4PiX</h1>
      <div class="about_us">
        <p> We are the 4PiX team in London and our mission is to revolutionize the world of the photography. We guarantee the highest quality of work and strive to provide exceptional customer service. Please feel free to contact us with questions, concerns or recommendations. We're always interested in making 4PiX better for <em>you!</em></p>
      </div>
      <h2 class="meet_us links">Meet the Team</h2>
    </div>

    <% @admins.each_slice(3) do |admins| %>
      <div class="row">
        <% admins.each do |admin| %>
          <div class="span4">
            <% cycle("1","2","3") %>
          <div class="photo_about">
            <h3><%= admin.first_name %> <% admin.last_name %></h3>
            <%= link_to image_tag(admin.avatar), user_path(admin) %><br/>
            <p><%= admin.biography %></p>
          </div>
        </div>
          <% if current_cycle == '1' %>
              <script>
              $( "div" ).last().addClass( "tilted1" );
              </script>
          <% end %>
          <% if current_cycle == '3' %>
              <script>
              $( "div" ).last().addClass( "tilted2" );
              </script>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
<br>
<br>
</div>

app/views/users/edit.html.erb
<div class="span8">
  <h1 class="inner_shadow">Edit Profile</h1>
  <br>
  <br>
  <%= render 'form' %>
<br>
<br>
</div>

app/views/users/index.html.erb
<div class="span10 offset1 photo">
<br>
<br>
    <h1 class="inner_shadow">4PiX Members</h1>
    <br>
    <table class="table">
      <tr>
        <th> </th>
        <th><em>Full Name</em></th>
        <th><em>Username</em></th>
        <th><em>Location</em></th>
        <th></th>
      </tr>

    <% @users.each do |user| %>
      <tr>

        <td>
            <% if user.avatar? %>
                <%= link_to( image_tag(user.avatar.thumb.url), user) %>
            <% end %>
        </td>
        <td><%= user.first_name %> <%= user.last_name %></td>
        <td><%= user.username.humanize %></td>
        <td><%= user.location %></td>
        <td><%= link_to 'View', user, class:"btn btn-info btn-mini" %>
                <% if current_user == user %>
                    <%= link_to 'Edit', edit_user_registration_path(user), class:"btn btn-warning btn-mini" %>
                <% end %>
                <%if can? :update, user and current_user.role == 'registered' || 'admin' %>
                    <%= link_to 'Destroy', user, class:"btn btn-danger btn-mini", method: :delete, data: { confirm: 'Are you sure?' } %>
                <%end%></td>
      </tr>
    <% end %>
    </table>

    <br />
<!--     <div class="links">
        < %= link_to 'New User', new_user_registration_path, class:"btn btn-success btn-large" %>
    </div> -->
<br>
<br>
    <div class="links">
        <%= paginate @users %>
    </div>
</div>

app/views/users/new.html.erb
<div class="span8">
  <h1 class="inner_shadow">Sign Up</h1>
  <br>
  <br>
  <%= render 'form' %>
<br>
<br>
</div>
<br>
<br>

app/views/users/show.html.erb
<div class="span12">
  <div class="user_profile">
    <p id="notice"><%= notice %></p>
    <div class="profile_block">
        <div class="row">
            <div class="span3">
              <% if @user.avatar? %>
                <%= image_tag @user.avatar.detail.url, class:"img-rounded"  %>
                <% end %>
            </div>
            <div class="span9" id="details">
                <div class="user_name">
                    <h1><%=@user.first_name%> <%=@user.last_name%></h1>
                </div>
                <div class="user_info">
                    <p>Biography:
                      <%= @user.biography %>
                    </p>
                    <p>
                      <b>Location:</b>
                      <%= @user.location %>
                    </p>
                    <p>
                      <b>Email:</b>
                      <%= @user.email %>
                    </p>
                    <p>
                      <b>Username:</b>
                      <%= @user.username %>
                    </p>
                  </div>
            </div>
        </div>
    </div>
</div>


<% if @user.albums.size > 8 %>
  <div class="links">
    <% if can? :update, @user %>
      <%= link_to 'Create Album', new_user_album_path(@user), class:"btn btn-success btn-mini" %>
      <%= link_to 'Edit your Profile', edit_user_registration_path(@user), class:"btn btn-warning btn-mini" %>
    <%end%>
    <%= link_to 'Back to Members Page', users_path, class:"btn btn-inverse btn-mini" %>
  </div>
<% end %>



<div class="user_albums">
  <p>
    <b><%= @user.username.humanize %>'s Albums:</b>
  </p>
</div>

  <div class="row">
    <% @user.albums.each do |album|%>
      <div class="span3 imglist">
        <% cycle("1","2","3","4","5") %>
          <div class="photo">
            <% if album.photos.size != 0 %>
              <b><%= link_to( image_tag(album.photos.first.photo_picture.thumb.url),  user_album_path(album.user, album))%></b>
            <% end %>
            <b><%= link_to album.name, user_album_path(album.user, album) %></b>
          </div>
        </div>
        <% if current_cycle == '2' %>
            <script>
            $( "div" ).last().addClass( "tilted1" );
            </script>
        <% end %>
        <% if current_cycle == '4' %>
            <script>
            $( "div" ).last().addClass( "tilted2" );
            </script>
        <% end %>
        <% if current_cycle == '5' %>
            <script>
            $( "div" ).last().addClass( "tilted3" );
            </script>
        <% end %>
      <% end %>
    </div>
<br>
<br>
  <div class="links">
    <% if can? :update, @user %>
      <%= link_to 'Create Album', new_user_album_path(@user), class:"btn btn-success btn-mini" %>
      <%= link_to 'Edit your Profile', edit_user_registration_path(@user), class:"btn btn-warning btn-mini" %>
    <%end%>
    <%= link_to 'Back to Members Page', users_path, class:"btn btn-inverse btn-mini" %>
  </div>
<br>
<br>
</div>

app/views/users/thanks_for_registering.html.erb
<%= content_for :page_title, 'Thanks for Registering' %>
<br>
<br>
<br>
<div class="links">
  Hold tight! We are processing your registration. <br><br>
  You should receive an email to confirm shortly. <br><br>
  Quick, go check your email!
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
</div>