config/routes.rb
Project2::Application.routes.draw do

  devise_for :user, controllers: {omniauth_callbacks: "omniauth_callbacks", registrations: "registrations" }

  devise_scope :user do
    get '/login', to: 'devise/sessions#new'
  end

  resources :users, except: [:new, :create, :update, :edit] do
    resources :albums do
      resources :photos do
        member do
          post '/comment', action: 'create', controller: 'comments'
          post :like_wall
          post :unlike_wall
          post :like
          post :unlike
          get :download
        end
      end
    end
  end

  resources :comments
  resources :pages
  resources :local_photos, only: :show

  get '/photo_wall', to: 'photos#photo_wall', as: :photo_wall
  get '/my_profile', to: 'users#my_profile', as: :my_profile
  match 'search', to: 'search#index', via: [:get, :post], as: :search

  resources :albums do
    get 'page/:page', action: :index, on: :collection
  end

 get '/about', to: 'users#about', as: :about
 get '/thanks_for_registering', to: 'users#thanks_for_registering', as: :thanks_for_registering


  root to: 'photos#photo_wall'

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  acts_as_votable
  acts_as_taggable
  # acts_as_taggable_on :photo_tags

  attr_accessible :description, :name, :photo_picture, :album_id, :tag_list

  mount_uploader :photo_picture, PhotoPictureUploader

  validates :name, presence: true
  validates :description, length:{ maximum: 250,
  	too_long: "%{count} characters is the maximum allowed."}
  validates :photo_picture, presence: true

  validate :photo_picture_size_validation

  belongs_to :album
  has_many :comments


  private
  def photo_picture_size_validation
    errors[:photo_picture, "Photo"] << "should be less than 1MB" if photo_picture.size > (1.2).megabyte
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
 load_and_authorize_resource

# Photo wall methods
  def photo_wall
    @photos = Photo.order(:cached_votes_total)
    # render :photo_wall
  end

  def like_wall
      @user = User.find(params[:user_id])
      @album = Album.find(params[:album_id])
      @photo = Photo.find(params[:id])
      @photo.liked_by current_user
      redirect_to :photo_wall
  end

  def unlike_wall
      @user = User.find(params[:user_id])
      @album = Album.find(params[:album_id])
      @photo = Photo.find(params[:id])
      @photo.disliked_by current_user
      redirect_to :photo_wall
  end


# Voting methods
  def like
    if params[:id]
      @photo = Photo.find(params[:id])
      @photo.liked_by current_user
      redirect_to user_album_photo_path(@photo.album.user, @photo.album, @photo)
    end
  end

  def unlike
    if params[:id]
      @photo = Photo.find(params[:id])
      @photo.disliked_by current_user
      redirect_to user_album_photo_path(@photo.album.user, @photo.album, @photo)
    end
  end

  def download
    @photo = Photo.find(params[:id])
    send_file ActionController::Base.helpers.asset_path(@photo.photo_picture.path), disposition: 'attachment'
  end


  # GET /photos
  # GET /photos.json
  def index
    @user = User.find(params[:user_id])
    @album = Album.find(params[:album_id])


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photos }
    end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @user = User.find(params[:user_id])
    @album = Album.find(params[:album_id])
    @photo = Photo.find(params[:id])
    @comment = Comment.new


    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
     @album = Album.find(params[:album_id])
      @photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photos }
    end
  end

  # GET /photos/1/edit
  def edit
    @album = Album.find(params[:album_id])
    @photo = Photo.find(params[:id])

  end

  # POST /photos
  # POST /photos.json
  def create
    @album = Album.find(params[:album_id])
    @photo = @album.photos.build(params[:photo])


    respond_to do |format|
      if @photo.save
        format.html { redirect_to user_album_path(@album.user, @album), notice: 'Photo successfully created.' }
        format.json { render json: @photo, status: :created, location: @photo }
      else
        format.html { render action: "new" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end


  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @photo = Photo.find(params[:id])


    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to user_album_photo_path(@photo.album.user, @photo.album, @photo), notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @album = Album.find(params[:album_id])
    @photo = Photo.find(params[:id])

    @photo.destroy

    respond_to do |format|
      format.html { redirect_to user_album_path(@album.user, @album) }
      format.json { head :no_content }
    end
  end
end

app/views/photos/_form.html.erb
<div class="span4 offset4 photo">
<%= form_for [@album.user, @album, @photo] do |f| %>

  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <br>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %><br />
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, size: '100x3' %><br />
  </div>

  <div class="field">
    <%= f.file_field :photo_picture, :onchange =>"validateFiles(this);", :data => { :max_file_size => 1.megabyte } %>
     <%= f.label :photo_picture%><br />
  </div>

  <div class="field">
    <%= f.label :tag_list %> <i>Please separate tags with a comma.</i><br />
    <%= f.text_field :tag_list %>
  </div>

  <div class="links">
    <%= f.submit 'Submit', class: "btn btn-success btn-mini" %>
    <%= link_to 'Cancel', user_album_path(@album.user, @album), class:"btn btn-inverse btn-mini" %>
  </div>
<% end %>
</div>

app/views/photos/edit.html.erb
<div class="span8">
  <h1 class="inner_shadow">Edit Photo</h1>
  <br>
  <br>
  <%= render 'form' %>
<br>
<br>
</div>

app/views/photos/index.html.erb
<div class="span8">
  <h1 class="inner_shadow">Index Photos</h1>
  <br>
  <br>
    <div class="links">
    <%= link_to 'Add Photo', new_user_album_photo_path, class:"btn btn-success btn-large" %>
    </div>
  <br>
  <table class="table">
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Photo picture</th>
      <th>Album</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

  <% @photos.each do |photo| %>
    <tr>
      <td><%= photo.name %></td>
      <td><%= photo.description %></td>
      <td><%= image_tag photo.photo_picture.url %></td>
      <td><%= photo.album_id %></td>
      <td><%= link_to 'View', user_album_photo_path(photo.album.user, photo.album, photo), class:"btn btn-info btn-mini" %></td>
      <td><%= link_to 'Edit', edit_user_album_photo_path(photo.album.user, photo.album, photo), class:"btn btn-warning btn-mini" %></td>
      <td><%= link_to 'Destroy', [photo.album.user,photo.album,photo], class:"btn btn-danger btn-mini", method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </table>

  <br />
  <div class="links">
    <%= link_to 'Add Photo', new_user_album_photo_path, class:"btn btn-success btn-large" %>
  </div>
<br>
<br>
</div>

<%= paginate @photos %>

app/views/photos/new.html.erb
<div class="span8">
  <h1 class="inner_shadow">Upload New Photo</h1>
  <br>
  <br>
  <%= render 'form' %>
<br>
<br>
</div>
<br>
<br>

app/views/photos/photo_wall.html.erb
<div class="span12">
<br>
<br>
<h1 class="links inner_shadow">4PiX's Wall of Fame</h1>
<h3 class="links">{ PiX of the Week }</h3>
<br>
<br>
  <div id="portfolio">
  <% if @photos %>
  <% @photos.each do |photo| %>
    <div class="item photo_on_wall">

      <%= image_tag local_photo_path(photo), :data => {:id => photo.id, :'full-width' => photo.photo_picture.image_width, :'full-height' => photo.photo_picture.image_height }, :id => "thumb_#{photo.id}", :class =>"thumb", :width => 160 %>

      <div class="info">
        <%= image_tag local_photo_path(photo), :data => {:id => photo.id}, :id => "full_#{photo.id}",:class => "full" %>

          <div class="votes">
            <b>Number of Likes:</b>
            <%= photo.likes.size %> |
            <%= link_to "Download full size", download_user_album_photo_path(photo.album.user, photo.album, photo) %>
          </div>

<% if false %>
           <div class="voting">
            <% if current_user %>
              <% if current_user.voted_up_on? photo %>
                <%= button_to 'Unlike', unlike_wall_user_album_photo_path(photo.album.user, photo.album, photo) %>
                <% else %>
                  < %= button_to 'Like', like_wall_user_album_photo_path(photo.album.user, photo.album, photo) %>
                <% end %>
              <%end%>
            </div>
<% end %>

            <div>
            <p>Leave a <%=link_to("comment", user_album_photo_path(photo.album.user, photo.album, photo)) %>, look at the full <%=link_to("album", user_album_path(photo.album.user, photo.album)) %>, or check out more of <%=photo.album.user.username.humanize %>'s photography <%= link_to("here", user_path(photo.album.user))%>!</p>
            </div>
        </div>

    </div>
  <% end %>
  </div>
<%end%>
<br>
<br>
</div>
<br>
<br>

app/views/photos/show.html.erb
<div class="span12">
  <br>
  <br>
  <h1 class="inner_shadow"><%= @photo.name %></h1>
  <p>
    <b><em>by <%= @photo.album.user.username %></em></b>
  </p>
  <br>
  <% if @photo.description? %>
    <p>
      <b>"<%= @photo.description %>"</b>
    </p>
  <% end %>
  <br>

    <div class = "links">
    <%= image_tag @photo.photo_picture.url, class:"photo" %>
    </div>

    <div class="voting">
      <b>Number of Likes: <%= @photo.likes.size %></b>
        <% if can? [:like, :unlike], @photo %>
          <% if current_user.voted_up_on? @photo %>
            <%= button_to 'Unlike', unlike_user_album_photo_path(@photo.album.user, @photo.album, @photo), class: "btn"  %>
          <% else %>
            <%= button_to 'Like', like_user_album_photo_path(@photo.album.user, @photo.album, @photo), class: "btn" %>
          <% end %>
        <% else %>
        <%end%>
        <%= link_to "Download full size", download_user_album_photo_path(@photo.album.user, @photo.album, @photo), class: "btn" %>
    </div>
    <br>
  <p>
    <b>Tags:</b>
    <%= @photo.tag_list %>
  </p>

  <div class="comments_container">
    <h3> Comments: </h3>
    <%unless current_user %>
      <p> Please <%= link_to 'log in', login_path %> to leave a comment </p>
    <% end %>

    <div class="photo_comments">
      <% @photo.comments.each do |comment| %>
          <% if comment.user.avatar? %>
            <%= image_tag comment.user.avatar.mini.url %>
          <% end %>
            "<%= comment.content %>"
            <%= comment.user.username %> on <%= comment.created_at.strftime('%c') %>
          <%if can? :destroy, comment %>
            <%=link_to 'delete', comment_path(comment.id), method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
      <% end %>
    </div><br>

      <%= render partial: "comments/form" if can? :create, @comment %>
  </div>

  <br>
  <br>
  <div class="links">
    <% if can? :manage, @photo.album.user %>
      <%= link_to 'Edit', edit_user_album_photo_path(@photo.album.user, @photo.album, @photo), class:"btn btn-warning btn-mini" %>
      <%= link_to 'Destroy', user_album_photo_path(@photo.album.user, @photo.album, @photo), class:"btn btn-danger btn-mini", method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
    <%= link_to 'Back to Album', user_album_path(@photo.album.user, @photo.album), class:"btn btn-inverse btn-mini" %>
  </div>
<br>
<br>
</div>