config/routes.rb
Project2::Application.routes.draw do

  devise_for :user, controllers: {omniauth_callbacks: "omniauth_callbacks", registrations: "registrations" }

  devise_scope :user do
    get '/login', to: 'devise/sessions#new'
  end

  resources :users, except: [:new, :create, :update, :edit] do
    resources :albums do
      resources :photos do
        member do
          post '/comment', action: 'create', controller: 'comments'
          post :like_wall
          post :unlike_wall
          post :like
          post :unlike
          get :download
        end
      end
    end
  end

  resources :comments
  resources :pages
  resources :local_photos, only: :show

  get '/photo_wall', to: 'photos#photo_wall', as: :photo_wall
  get '/my_profile', to: 'users#my_profile', as: :my_profile
  match 'search', to: 'search#index', via: [:get, :post], as: :search

  resources :albums do
    get 'page/:page', action: :index, on: :collection
  end

 get '/about', to: 'users#about', as: :about
 get '/thanks_for_registering', to: 'users#thanks_for_registering', as: :thanks_for_registering


  root to: 'photos#photo_wall'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:page_title) %></title>
  <link href='http://fonts.googleapis.com/css?family=Kameron' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Oxygen:300' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>


<!--           <div class="span9">
            <h1><img id="logo" src="../assets/Logo.png"></h1>
          </div>
          <div class="popup_login span3">
              < % if current_user %>
                <div class="logged-in">
                  < %=image_tag current_user.user_picture.thumb.url, class: "img-circle"%>
                  Logged in as < %= current_user.username %>
                </div>
              < % end %>
          </div>
        </div> -->

  <div class="navbar navbar-inverse">
    <nav class="navbar-inner">
      <ul class ="nav">
        <li class="active"><%= link_to("4PiX", photo_wall_path) %></li>

        <li><%= link_to('Members', users_path)  %></li>

        </li>
        <% if current_user %>
          <li><%= link_to('My Profile', my_profile_path) %></li>
        <% end %>
      </ul>


      <ul class="nav pull-right">
        <li>
          <%= form_tag search_path, class:"navbar-search pull-left", html: {method: :post} do |f| %>
            <%= text_field_tag :q, params[:q], class:"search-query" %>
            <%= submit_tag 'Search!' , name: nil,  class:"btn btn-inverse btn-small" %>
          <% end %>
        </li>
        <% unless current_user %>
        <li class="nav-signup"><%= link_to('Sign up', new_user_registration_path)  %></li>
        <% end %>
        <li class="nav-user">
          <% if current_user %>
            <%= link_to "Log Out, #{current_user.username.humanize}!" , destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% else %>
            <%= link_to 'Login', login_path %>
          <% end %>
        </li>
      </ul>

    </nav>
  </div>

  <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    <div class="footer">
      <p>Made with organically grown, locally sourced code. Meet the <%= link_to('4PiX Team!', about_path) %></p>
    </div>
  </div>

<style type="text/css">
  body {
    background: url(<%= raw randomized_background_image %>) no-repeat center center fixed;
      -webkit-background-size: cover;
      -moz-background-size: cover;
      -o-background-size: cover;
      background-size: cover;
    }
</style>


</body>
</html>